### ISSUE TITLE
Missing leave events

### ISSUE THREAD

**Issue by lagden** [metafizzy/unipointer#2]
https://github.com/metafizzy/unipointer/blob/master/unipointer.js#L143

`mouseleave`, `touchleave`, `pointerleave` and `MSPointerLeave`

``` javascript
var postStartEvents = {
  mousedown: [ 'mousemove', 'mouseup', 'mouseleave' ],
  touchstart: [ 'touchmove', 'touchend', 'touchcancel', 'touchleave' ],
  pointerdown: [ 'pointermove', 'pointerup', 'pointercancel', 'pointerleave' ],
  MSPointerDown: [ 'MSPointerMove', 'MSPointerUp', 'MSPointerCancel', 'MSPointerLeave' ]
};
```

I know that just putting this way will not make any difference.

http://lagden.github.io/fragment/

**Comment by desandro** [comment]
Thanks for requesting this feature. The enter and leave pointer events are outside the scope of how I use Unipointer. If you require them, you may better off either forking Unipointer, or developing your own custom solution
