### ISSUE TITLE
elem[ bindMethod ]( startEvent, this );

### ISSUE THREAD

**Issue by LeeeeeeM** [metafizzy/unipointer#6]
hello,desandro,i'm a new born.

```
elem[ bindMethod ]( startEvent, this );
```
i wonder what is 'this' means. i'm confusing.

**Comment by desandro** [comment]
Thanks for this question! I wrote up a whole blog post: [What is `this` in event listeners?](https://metafizzy.co/blog/this-in-event-listeners/)
