### ISSUE TITLE
why the pointerDown event just trigger?

### ISSUE THREAD

**Issue by sably** [metafizzy/unipointer#7]
when i  overwrite public pointer methods ( pointerDown, pointerMove, pointerUp and pointerCancel)
the pointerDown event just trigger and other not. Why?

**Comment by sably** [comment]
PointerFun.prototype.pointerDown = function( event, pointer ) {
        console.log('pointer down');
        this._bindPostStartEvents( event );//i think this must be added
    };

**Comment by desandro** [comment]
Thanks for reporting this issue. Could you put together a live demo I could take a look at, like on CodePen or other demo site?
